image: node:20

stages:
  - build

before_script:
  - apt-get update && apt-get install -y libwebkit2gtk-4.0-dev
  - npm ci

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
